### PR TITLE
good pep8

### PR DESCRIPTION
**Pull request by unazed**

### CODE REVIEW

**Comment by Aareon** [comment]
Please commit to a single patch instead of creating a bunch of tiny tiny PRs.

**Comment by unazed** [comment]
my bad

**Comment by Aareon** [comment]
There is not a single thing in this PR that is even negligibly close to being PEP-8 compliant. Why have you gone and moved parens and brackets to their own separate lines? It serves no functional purpose, nor makes it any more readable.

Secondly, when did we start to use `while 1` in lew of `while True`? Granted, there’s no functional difference, but that same argument could be used in regards to why you changed this at all.

Thirdly, even though 0 is falsy, does not mean that using `not` is the correct way to do this. The original way was the most Pythonic and acceptable option of the two.

Yet another pointless PR in my opinion.

**Comment by unazed** [comment]
the parens/brackets are moreover a stylistic choice

`while 1` seems to be a bit controversial between jason since the only
place where it does help performance is python 2 which i like to consider
when programming

`if not x` is more pythonic than `if x == 0`, `not operator is used to
invert the truth value.`, not only is it faster but it's shorter and more
readable because it uses *english* keywords

**Comment by Jason2605** [comment]
Im going to close this due to the fact I'm going to be removing the while loop anyways, the redis module provides a scan_iter method which means i don't need to handle the cursor.

**Pull request closed without merging**
